name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
        
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        
    - name: Create an installer
      run: |
        pyinstaller goesr-grabber.py

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: goesr-grabber
        # A file, directory or wildcard pattern that describes what to upload
        path: dist/*
        if-no-files-found: error
        retention-days: 0
